name: github pages

on:
  workflow_dispatch:
  push:
    branches: [main, showroom]
    paths-ignore:
      - "README.adoc"
      - ".gitignore"

permissions:
  pages: write
  id-token: write

concurrency:
  group: gh-pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout main
        uses: actions/checkout@v4
        with:
          ref: main
          path: main-branch
      - name: checkout showroom
        uses: actions/checkout@v4
        with:
          ref: showroom
          path: showroom-branch
      - name: configure pages
        uses: actions/configure-pages@v5
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.13.1
      - name: install antora
        run: npm install --global @antora/cli@3.1 @antora/site-generator@3.1
      - name: build main branch
        working-directory: main-branch
        run: antora generate default-site.yml --stacktrace
      - name: build showroom branch
        working-directory: showroom-branch
        run: antora generate default-site.yml --stacktrace
      - name: combine sites
        run: |
          mkdir -p www
          cp -r showroom-branch/www/* www/
          mkdir -p www/next
          cp -r main-branch/www/* www/next/
      - name: upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: www
  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - name: deploy github pages
      id: deployment
      uses: actions/deploy-pages@v4
